routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () { 
	return view('auth.login');
})->middleware('guest');

Auth::routes(['verify' => false, 'register' => false]);

Route::get('/home', 'HomeController@index')->name('home');

Route::get('instructors', 'userController@instructors_view')->name('instructors.index');
Route::post('instructors', 'userController@instructors_store')->name('instructors.store');
Route::get('instructors/create', 'userController@instructors_create')->name('instructors.create');
Route::get('instructors/{instructor}/edit', 'userController@instructors_edit')->name('instructors.edit');

Route::get('students', 'userController@students_view')->name('students.index');
Route::get('mycourses', 'courseController@myCourses')->name('mycourses');
Route::post('students', 'userController@students_store')->name('students.store');
Route::get('students/create', 'userController@students_create')->name('students.create');
Route::get('students/{student}/edit', 'userController@students_edit')->name('students.edit');
Route::post('takecourse/{course}', 'userController@takeCourse')->name('takecourse');
Route::post('leavecourse/{course}', 'userController@leaveCourse')->name('leavecourse');

Route::resource('courses', 'courseController')->except('show');
Route::resource('users', 'userController')->only(['update','destroy']);

resources/views/students/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">
                    {{__("Students")}}
                    <a class="btn btn-secondary float-right btn-sm" href="{{route('students.index')}}"><i class="fa fa-arrow-left"></i></a>

                </div>

                <div class="card-body">
                    @if (session('status'))
                    <div class="alert alert-success" role="alert">
                        {{ session('status') }}
                    </div>
                    @endif
                    <form method="POST" action="{{ route('students.store') }}" class="needs-validation" novalidate>
                        @csrf
                        <div class="form-row">
                            <div class="col-md-4 mb-3">
                                <label for="first_name">{{ __("First name") }}</label>
                                <input type="text" class="form-control @error('first_name') is-invalid @enderror" name="first_name" id="first_name" placeholder="{{__('First name') }}" value="{{ old('first_name') }}" required>
                                @error('first_name')
                                <div class="invalid-feedback" role="alert">
                                    <strong>{{ $errors->first('first_name') }}</strong>
                                </div>
                                @enderror
                                <div class="invalid-feedback">
                                    {{__("Please enter your ")." ".strtolower(__("First name"))}}
                                </div>
                            </div>
                            <div class="col-md-4 mb-3">
                                <label for="last_name">{{__("Last name") }}</label>
                                <input type="text" class="form-control @error('last_name') is-invalid @enderror" name="last_name" id="last_name" placeholder="{{__('Last name') }}" value="{{ old('last_name') }}" required>

                                @error('last_name')
                                <div class="invalid-feedback" role="alert">
                                    <strong>{{ $errors->first('last_name') }}</strong>
                                </div>
                                @enderror
                                <div class="invalid-feedback">
                                    {{__("Please enter your ")." ".Str::lower(__("Last name"))}}
                                </div>
                            </div>
                            <div class="col-md-4 mb-3">
                                <label for="identification">{{__("Identification") }}</label>
                                <input type="text" class="form-control @error('identification') is-invalid @enderror" name="identification" id="identification" placeholder="{{__('Identification') }}" value="{{ old('identification') }}" required>
                                @error('identification')
                                <div class="invalid-feedback" role="alert">
                                    <strong>{{ $errors->first('identification') }}</strong>
                                </div>
                                @enderror
                                <div class="invalid-feedback">
                                    {{__("Please enter your ")." ".Str::lower(__("Identification"))}}
                                </div>
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="col-md-4 mb-3">
                                <label for="phone">{{__("Phone") }}</label>
                                <input type="text" class="form-control @error('phone') is-invalid @enderror" name="phone" id="phone" placeholder="{{__('Phone') }}" value="{{ old('phone') }}" required>
                                @error('phone')
                                <div class="invalid-feedback" role="alert">
                                    <strong>{{ $errors->first('phone') }}</strong>
                                </div>
                                @enderror
                                <div class="invalid-feedback">
                                    {{__("Please enter your ")." ".Str::lower(__("Phone"))}}
                                </div>
                            </div>
                            <div class="col-md-8 mb-3">
                                <label for="email">{{__("Email") }}</label>
                                <input type="email" class="form-control @error('email') is-invalid @enderror" name="email" id="email" placeholder="{{__('Email') }}" value="{{ old('email') }}" required>
                                @error('email')
                                <div class="invalid-feedback" role="alert">
                                    <strong>{{ $errors->first('email') }}</strong>
                                </div>
                                @enderror
                                <div class="invalid-feedback">
                                    {{__("Please enter your ")." ".Str::lower(__("Email"))}}
                                </div>
                            </div>
                        </div>
                        <hr>
                        <button class="btn btn-secondary" type="reset">{{__("Restart")}}</button>
                        <button class="btn btn-primary float-right" type="submit">{{__("Save")}}</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/students/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">
                    {{__("Students")}}
                    <a class="btn btn-secondary float-right btn-sm" href="{{route('students.index')}}"><i class="fa fa-arrow-left"></i></a>

                </div>

                <div class="card-body">
                    @if (session('status'))
                    <div class="alert alert-success" role="alert">
                        {{ session('status') }}
                    </div>
                    @endif
                    <form method="POST" action="{{ route('users.update',$student['id']) }}" class="needs-validation" novalidate>
                        @method('PUT')
                        @csrf
                        <div class="form-row">
                            <div class="col-md-4 mb-3">
                                <label for="first_name">{{ __("First name") }}</label>
                                <input type="text" class="form-control @error('first_name') is-invalid @enderror" name="first_name" id="first_name" placeholder="{{__('First name') }}" value="{{ $student['first_name'] }}" required>
                                @error('first_name')
                                <div class="invalid-feedback" role="alert">
                                    <strong>{{ $errors->first('first_name') }}</strong>
                                </div>
                                @enderror
                                <div class="invalid-feedback">
                                    {{__("Please enter your ")." ".strtolower(__("First name"))}}
                                </div>
                            </div>
                            <div class="col-md-4 mb-3">
                                <label for="last_name">{{__("Last name") }}</label>
                                <input type="text" class="form-control @error('last_name') is-invalid @enderror" name="last_name" id="last_name" placeholder="{{__('Last name') }}" value="{{ $student['last_name'] }}" required>

                                @error('last_name')
                                <div class="invalid-feedback" role="alert">
                                    <strong>{{ $errors->first('last_name') }}</strong>
                                </div>
                                @enderror
                                <div class="invalid-feedback">
                                    {{__("Please enter your ")." ".Str::lower(__("Last name"))}}
                                </div>
                            </div>
                            <div class="col-md-4 mb-3">
                                <label for="identification">{{__("Identification") }}</label>
                                <input type="text" class="form-control @error('identification') is-invalid @enderror" name="identification" id="identification" placeholder="{{__('Identification') }}" value="{{ $student['identification'] }}" required>
                                @error('identification')
                                <div class="invalid-feedback" role="alert">
                                    <strong>{{ $errors->first('identification') }}</strong>
                                </div>
                                @enderror
                                <div class="invalid-feedback">
                                    {{__("Please enter your ")." ".Str::lower(__("Identification"))}}
                                </div>
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="col-md-4 mb-3">
                                <label for="phone">{{__("Phone") }}</label>
                                <input type="text" class="form-control @error('phone') is-invalid @enderror" name="phone" id="phone" placeholder="{{__('Phone') }}" value="{{ $student['phone'] }}" required>
                                @error('phone')
                                <div class="invalid-feedback" role="alert">
                                    <strong>{{ $errors->first('phone') }}</strong>
                                </div>
                                @enderror
                                <div class="invalid-feedback">
                                    {{__("Please enter your ")." ".Str::lower(__("Phone"))}}
                                </div>
                            </div>
                            <div class="col-md-8 mb-3">
                                <label for="email">{{__("Email") }}</label>
                                <input type="email" class="form-control @error('email') is-invalid @enderror" name="email" id="email" placeholder="{{__('Email') }}" value="{{ $student['email'] }}" required>
                                @error('email')
                                <div class="invalid-feedback" role="alert">
                                    <strong>{{ $errors->first('email') }}</strong>
                                </div>
                                @enderror
                                <div class="invalid-feedback">
                                    {{__("Please enter your ")." ".Str::lower(__("Email"))}}
                                </div>
                            </div>
                        </div>
                        <hr>
                        <button class="btn btn-secondary" type="reset">{{__("Restart")}}</button>
                        <button class="btn btn-primary float-right" type="submit">{{__("Update")}}</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/students/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-10">
            <div class="card">
                <div class="card-header">
                    {{__("Students")}}
                    <a class="btn btn-secondary float-right btn-sm" href="{{route('home')}}"><i class="fa fa-arrow-left"></i></a>
                    @if (auth()->user()->hasRole(1))
                    <a class="btn btn-primary mr-2 float-right btn-sm" href="{{route('students.create')}}"><i class="fa fa-plus"></i></a>
                    @endif

                </div>

                <div class="card-body">
                    @if (session('status'))
                    <div class="alert alert-success" role="alert">
                        {{ session('status') }}
                    </div>
                    @endif
                    {{-- <div class="users">
                        @include('students.table')
                    </div> --}}
                    @if(!$students->isEmpty())

                    <div class="table-responsive">
                        <table class="table table-striped table-sm">
                            <thead class="thead-light">
                                <tr>
                                    <th scope="col">{{__("First name")}}</th>
                                    <th scope="col">{{__("Last name")}}</th>
                                    <th scope="col">{{__("Identification")}}</th>
                                    <th scope="col">{{__("Phone")}}</th>
                                    <th scope="col">{{__("Email")}}</th>
                                    @if (auth()->user()->rol===2)
                                    <th scope="col">{{__("Course")}}</th>
                                    @endif
                                    @if (auth()->user()->hasRole(1))
                                    <th scope="col"></th>
                                    @endif
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($students as $student)
                                <tr>
                                    <td>{{$student['first_name']}}</td>
                                    <td>{{$student['last_name']}}</td>
                                    <td>{{$student['identification']}}</td>
                                    <td>{{$student['phone']}}</td>
                                    <td>{{$student['email']}}</td>
                                    @if (auth()->user()->rol===2)
                                    <td>
                                        @foreach($student->courses as $course)
                                        @if ($course->created_by===auth()->user()->id)
                                        <a href="{{ route('courses.edit',$course->id) }}">{{$course->name}}</a>|
                                        @endif
                                        @endforeach
                                    </td>
                                    @endif
                                    @if (auth()->user()->hasRole(1))
                                    <td>
                                        <a class="btn btn-sm btn-primary" href="{{route('students.edit',$student->id)}}">
                                            <i class="fa fa-edit"></i>
                                        </a>
                                        <form method="POST" action="{{route('users.destroy',$student->id)}}" class="d-inline-block">
                                            @method('DELETE')
                                            <button class="btn-sm btn btn-danger delete" data-placement="left" data-tt="tooltip" title="{{__('Delete company')}}" data-id="{{ $student->id }}" data-ts="{{__('Are you sure?')}}"  data-tx='{{__("You won't be able to revert this!")}}' data-ty="{{__('Yes')}}">
                                                <i class="fa fa-trash"></i>
                                            </button>
                                            @csrf
                                        </form>
                                    </td> 
                                    @endif
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                    @else
                    <h5 class="text-center">
                        {{__("No record found")}}
                    </h5>
                    @endif
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/students/table.blade.php
@if(!$users->isEmpty())
<div id="load" class="position-relative">
    <div class="table-responsive mb-2">

        <table class="table table-striped table-sm min-1000 mb-0">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">{{__("Name")}}</th>
                    <th scope="col">{{__("Email")}}</th>
                    <th scope="col">{{__("Tipo")}}</th>
                    <th scope="col" class="text-center">{{__("Creation date")}}</th>
                    <th scope="col" class="text-center">{{__("Update date")}}</th>
                    @if (levelcheck('Super'))
                    <th scope="col" class="text-right">{{__("Actions")}}</th>
                    @endif
                </tr>
            </thead>
            <tbody>
                @foreach($users as $user)  
                <tr>
                    <td>{{ $user->id }}</td>
                    <td>{{ $user->name }}</td>
                    <td>{{ $user->email }}</td>
                    <td>
                        @foreach ($user->roles->sortByDesc('name') as $rol)
                        @switch($rol->id)
                        @case(2)
                        {{ __("Administrator") }},
                        @break
                        @case(3)
                        {{ __("Storer") }},
                        @break
                        @case(4)
                        {{ __("Buyer") }},
                        @break
                        @default
                        
                        @endswitch
                        @endforeach
                    </td>
                    <td class="text-center">{{ $user->created_at }}</td>
                    <td class="text-center">{{ $user->updated_at }}</td>
                    @if (levelcheck('Super'))
                    <td class="text-right">
                        <a class="btn-sm btn btn-dark" data-placement="left" data-tt="tooltip" title="{{__('Edit user')}}" href="{{ route('users.edit',$user->id) }}">
                            <i class="fa fa-pen"></i>
                        </a>
                        <form method="POST" class="d-inline-block">
                            @method('DELETE')
                            <button class="btn-sm btn btn-danger delete" data-placement="left" data-tt="tooltip" title="{{__('Delete user')}}" data-id="{{ $user->id }}" data-ts="{{__('Are you sure?')}}"  data-tx='{{__("You won't be able to revert this!")}}' data-ty="{{__('Yes')}}">
                                <i class="fa fa-trash"></i>
                            </button>
                            @csrf
                        </form>
                    </td>
                    @endif
                </tr>
                @endforeach
            </tbody>
        </table>

    </div>
</div>

<div class="table-responsive">
    {{ $users->onEachSide(2)->links() }}
</div>
@else
<div id="load" class="position-relative">
    <div class="text-center mt-4">
        <p>
            {{__("No record found")}}
        </p>
        @if (levelcheck('Super'))
        <a class="btn  btn-sm btn-primary mt-1" href="{{ route('users.create') }}">
            <i class="fa fa-plus"></i> {{__("Add user")}}
        </a>
        @endif
    </div>
</div>
@endif