routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () { 
	return view('auth.login');
})->middleware('guest');

Auth::routes(['verify' => false, 'register' => false]);

Route::get('/home', 'HomeController@index')->name('home');

Route::get('instructors', 'userController@instructors_view')->name('instructors.index');
Route::post('instructors', 'userController@instructors_store')->name('instructors.store');
Route::get('instructors/create', 'userController@instructors_create')->name('instructors.create');
Route::get('instructors/{instructor}/edit', 'userController@instructors_edit')->name('instructors.edit');

Route::get('students', 'userController@students_view')->name('students.index');
Route::get('mycourses', 'courseController@myCourses')->name('mycourses');
Route::post('students', 'userController@students_store')->name('students.store');
Route::get('students/create', 'userController@students_create')->name('students.create');
Route::get('students/{student}/edit', 'userController@students_edit')->name('students.edit');
Route::post('takecourse/{course}', 'userController@takeCourse')->name('takecourse');
Route::post('leavecourse/{course}', 'userController@leaveCourse')->name('leavecourse');

Route::resource('courses', 'courseController')->except('show');
Route::resource('users', 'userController')->only(['update','destroy']);

resources/views/courses/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">
                    {{__("Courses")}}
                    <a class="btn btn-secondary float-right btn-sm" href="{{route('courses.index')}}"><i class="fa fa-arrow-left"></i></a>

                </div>

                <div class="card-body">
                    @if (session('status'))
                    <div class="alert alert-success" role="alert">
                        {{ session('status') }}
                    </div>
                    @endif
                    <form method="POST" action="{{ route('courses.store') }}" class="needs-validation" novalidate>
                        @csrf
                        <div class="form-row">
                            <div class="col-md-6 mb-3">
                                <label for="code">{{ __("Code") }}</label>
                                <input type="text" class="form-control @error('code') is-invalid @enderror" name="code" id="code" placeholder="{{__('Code') }}" value="{{ old('code') }}" required>
                                @error('code')
                                <div class="invalid-feedback" role="alert">
                                    <strong>{{ $errors->first('code') }}</strong>
                                </div>
                                @enderror
                                <div class="invalid-feedback">
                                    {{__("Please enter your ")." ".Str::lower(__("Code"))}}
                                </div>
                            </div>
                            <div class="col-md-6 mb-3">
                                <label for="name">{{__("Name") }}</label>
                                <input type="text" class="form-control @error('name') is-invalid @enderror" name="name" id="name" placeholder="{{__('Name') }}" value="{{ old('name') }}" required>

                                @error('name')
                                <div class="invalid-feedback" role="alert">
                                    <strong>{{ $errors->first('name') }}</strong>
                                </div>
                                @enderror
                                <div class="invalid-feedback">
                                    {{__("Please enter your ")." ".Str::lower(__("Name"))}}
                                </div>
                            </div>
                            
                        </div>
                        <div class="form-row">
                            <div class="col-md-12 mb-3">
                                <label for="description">{{__("Description") }}</label>
                                <textarea class="form-control @error('description') is-invalid @enderror" name="description" id="description" placeholder="{{__('Description') }}"  required>{{ old('description') }}</textarea>
                                @error('description')
                                <div class="invalid-feedback" role="alert">
                                    <strong>{{ $errors->first('description') }}</strong>
                                </div>
                                @enderror
                                <div class="invalid-feedback">
                                    {{__("Please enter your ")." ".Str::lower(__("Description"))}}
                                </div>
                            </div>
                            @if (auth()->user()->hasRole(1))
                            <div class="col-md-12 mb-3">
                                <label for="instructor">{{__("Instructor") }}</label>
                                <select class="custom-select @error('instructor') is-invalid @enderror" name="instructor" id="instructor" required>
                                    <option value="" selected>{{__("Select an instructor")}}</option>
                                    @foreach($instructors as $instructor)
                                    <option {{ old('instructor') == $instructor->id ? 'selected' : '' }} value="{{$instructor->id}}">
                                        {{$instructor->first_name.' '.$instructor->last_name}}
                                    </option>
                                    @endforeach
                                </select>
                                @error('instructor')
                                <div class="invalid-feedback" role="alert">
                                    <strong>{{ $errors->first('instructor') }}</strong>
                                </div>
                                @enderror
                                <div class="invalid-feedback">  
                                    {{__("Please enter your ")." ".Str::lower(__("instructor"))}}
                                </div>
                            </div>
                            @endif
                        </div>
                        <hr>
                        <button class="btn btn-secondary" type="reset">{{__("Restart")}}</button>
                        <button class="btn btn-primary float-right" type="submit">{{__("Save")}}</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/courses/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">
                    {{__("Courses")}}
                    <a class="btn btn-secondary float-right btn-sm" href="{{route('courses.index')}}"><i class="fa fa-arrow-left"></i></a>

                </div>

                <div class="card-body">
                    @if (session('status'))
                    <div class="alert alert-success" role="alert">
                        {{ session('status') }}
                    </div>
                    @endif
                    <form method="POST" action="{{ route('courses.update',$course['id']) }}" class="needs-validation" novalidate>
                        @method('PUT')
                        @csrf
                        <div class="form-row">
                            <div class="col-md-6 mb-3">
                                <label for="code">{{ __("Code") }}</label>
                                <input type="text" class="form-control @error('code') is-invalid @enderror" name="code" id="code" placeholder="{{__('Code') }}" value="{{$course->code }}" required>
                                @error('code')
                                <div class="invalid-feedback" role="alert">
                                    <strong>{{ $errors->first('code') }}</strong>
                                </div>
                                @enderror
                                <div class="invalid-feedback">
                                    {{__("Please enter your ")." ".Str::lower(__("Code"))}}
                                </div>
                            </div>
                            <div class="col-md-6 mb-3">
                                <label for="name">{{__("Name") }}</label>
                                <input type="text" class="form-control @error('name') is-invalid @enderror" name="name" id="name" placeholder="{{__('Name') }}" value="{{$course->name }}" required>

                                @error('name')
                                <div class="invalid-feedback" role="alert">
                                    <strong>{{ $errors->first('name') }}</strong>
                                </div>
                                @enderror
                                <div class="invalid-feedback">
                                    {{__("Please enter your ")." ".Str::lower(__("Name"))}}
                                </div>
                            </div>
                            
                        </div>
                        <div class="form-row">
                            <div class="col-md-12 mb-3">
                                <label for="description">{{__("Description") }}</label>
                                <textarea class="form-control @error('description') is-invalid @enderror" name="description" id="description" placeholder="{{__('Description') }}"  required>{{$course->description }}</textarea>
                                @error('description')
                                <div class="invalid-feedback" role="alert">
                                    <strong>{{ $errors->first('description') }}</strong>
                                </div>
                                @enderror
                                <div class="invalid-feedback">
                                    {{__("Please enter your ")." ".Str::lower(__("Description"))}}
                                </div>
                            </div>
                            @if (auth()->user()->hasRole(1))
                            <div class="col-md-12 mb-3">
                                <label for="instructor">{{__("Instructor") }}</label>
                                <select class="custom-select @error('instructor') is-invalid @enderror" name="instructor" id="instructor" required>
                                    <option value="" selected>{{__("Select an instructor")}}</option>
                                    @foreach($instructors as $instructor)
                                    <option {{$course->created_by == $instructor->id ? 'selected' : '' }} value="{{$instructor->id}}">
                                        {{$instructor->first_name.' '.$instructor->last_name}}
                                    </option>
                                    @endforeach
                                </select>
                                @error('instructor')
                                <div class="invalid-feedback" role="alert">
                                    <strong>{{ $errors->first('instructor') }}</strong>
                                </div>
                                @enderror
                                <div class="invalid-feedback">
                                    {{__("Please enter your ")." ".Str::lower(__("instructor"))}}
                                </div>
                            </div>
                            @endif
                        </div>
                        <hr>
                        <button class="btn btn-secondary" type="reset">{{__("Restart")}}</button>
                        <button class="btn btn-primary float-right" type="submit">{{__("Update")}}</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/courses/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-10">
            <div class="card">
                <div class="card-header">
                    {{__("Courses")}}
                    <a class="btn btn-secondary float-right btn-sm" href="{{route('home')}}"><i class="fa fa-arrow-left"></i></a>
                    @if (auth()->user()->hasRole(2))
                    <a class="btn btn-primary mr-2 float-right btn-sm" href="{{route('courses.create')}}"><i class="fa fa-plus"></i></a>
                    @endif

                </div>

                <div class="card-body">
                    @if (session('status'))
                    <div class="alert alert-success" role="alert">
                        {{ session('status') }} 
                        @if (auth()->user()->rol===3) |
                        <a href="{{ route('mycourses') }}">{{__("My courses")}}</a>
                        @endif
                    </div>
                    @endif
                    {{-- <div class="users">
                        @include('courses.table')
                    </div> --}}
                    @if(!$courses->isEmpty())
                    <div class="table-responsive">
                        <table class="table table-striped table-sm">
                            <thead class="thead-light">
                                <tr>
                                    <th scope="col">{{__("Name")}}</th>
                                    <th scope="col">{{__("Code")}}</th>
                                    <th scope="col">{{__("Description")}}</th>
                                    <th scope="col">{{__("Instructor")}}</th>
                                    @if (auth()->user()->hasRole(3))
                                    <th scope="col"></th>
                                    @endif
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($courses as $course)
                                <tr>
                                    <td>{{$course['name']}}</td>
                                    <td>{{$course['code']}}</td>
                                    <td>{{$course['description']}}</td>
                                    <td>{{$course->creator->first_name.' '.$course->creator->last_name}}</td>
                                    @if (auth()->user()->hasRole(2))
                                    <td>
                                        <a class="btn btn-sm btn-primary" href="{{route('courses.edit',$course->id)}}">
                                            <i class="fa fa-edit"></i>
                                        </a>
                                        @if (auth()->user()->hasRole(1))
                                        <form method="POST" action="{{route('courses.destroy',$course->id)}}" class="d-inline-block">
                                            @method('DELETE')
                                            <button class="btn-sm btn btn-danger delete" data-placement="left" data-tt="tooltip" title="{{__('Delete company')}}" data-id="{{ $course->id }}" data-ts="{{__('Are you sure?')}}"  data-tx='{{__("You won't be able to revert this!")}}' data-ty="{{__('Yes')}}">
                                                <i class="fa fa-trash"></i>
                                            </button>
                                            @csrf
                                        </form>
                                        @endif
                                    </td> 
                                    @endif
                                    @if (auth()->user()->rol===3)
                                    @if (auth()->user()->hasCourse($course->id))
                                    <td>
                                        <form method="POST" action="{{route('leavecourse',$course->id)}}" class="d-inline-block">
                                            <button class="btn-sm btn btn-danger"><i class="fa fa-sign-out-alt"></i> {{__('Leave the course')}}</button>
                                            @csrf
                                        </form>
                                    </td> 
                                    @else
                                    <td>
                                        <form method="POST" action="{{route('takecourse',$course->id)}}" class="d-inline-block">
                                            <button class="btn-sm btn btn-success"><i class="fa fa-sign-in-alt"></i> {{__('Enter the course')}}</button>
                                            @csrf
                                        </form>
                                    </td> 
                                    @endif
                                    @endif
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                    @else
                    <h5 class="text-center">
                        {{__("No record found")}}
                    </h5>
                    @endif
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/courses/mycourses.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-10">
            <div class="card">
                <div class="card-header">
                    {{__("Courses")}}
                    <a class="btn btn-secondary float-right btn-sm" href="{{route('home')}}"><i class="fa fa-arrow-left"></i></a>
                </div>

                <div class="card-body">
                    @if (session('status'))
                    <div class="alert alert-success" role="alert">
                        {{ session('status') }}
                    </div>
                    @endif
                    {{-- <div class="users">
                        @include('courses.table')
                    </div> --}}
                    @if(!$courses->isEmpty())
                    <div class="table-responsive">
                        <table class="table table-striped table-sm">
                            <thead class="thead-light">
                                <tr>
                                    <th scope="col">{{__("Name")}}</th>
                                    <th scope="col">{{__("Code")}}</th>
                                    <th scope="col">{{__("Description")}}</th>
                                    <th scope="col">{{__("Instructor")}}</th>
                                    @if (auth()->user()->hasRole(3))
                                    <th scope="col"></th>
                                    @endif
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($courses as $course)
                                <tr>
                                    <td>{{$course['name']}}</td>
                                    <td>{{$course['code']}}</td>
                                    <td>{{$course['description']}}</td>
                                    <td>{{$course->creator->first_name.' '.$course->creator->last_name}}</td>
                                    @if (auth()->user()->hasRole(2))
                                    <td>
                                        <a class="btn btn-sm btn-primary" href="{{route('courses.edit',$course->id)}}">
                                            <i class="fa fa-edit"></i>
                                        </a>
                                        @if (auth()->user()->hasRole(1))
                                        <form method="POST" action="{{route('courses.destroy',$course->id)}}" class="d-inline-block">
                                            @method('DELETE')
                                            <button class="btn-sm btn btn-danger delete" data-placement="left" data-tt="tooltip" title="{{__('Delete company')}}" data-id="{{ $course->id }}" data-ts="{{__('Are you sure?')}}"  data-tx='{{__("You won't be able to revert this!")}}' data-ty="{{__('Yes')}}">
                                                <i class="fa fa-trash"></i>
                                            </button>
                                            @csrf
                                        </form>
                                        @endif
                                    </td> 
                                    @endif
                                    <td>
                                        <form method="POST" action="{{route('leavecourse',$course->id)}}" class="d-inline-block">
                                            <button class="btn-sm btn btn-danger"><i class="fa fa-sign-out-alt"></i> {{__('Leave the course')}}</button>
                                            @csrf
                                        </form>
                                    </td> 
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                    @else
                    <h5 class="text-center">
                        {{__("No record found")}}
                    </h5>
                    @endif
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/courses/table.blade.php
@if(!$users->isEmpty())
<div id="load" class="position-relative">
    <div class="table-responsive mb-2">

        <table class="table table-striped table-sm min-1000 mb-0">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">{{__("Name")}}</th>
                    <th scope="col">{{__("Email")}}</th>
                    <th scope="col">{{__("Tipo")}}</th>
                    <th scope="col" class="text-center">{{__("Creation date")}}</th>
                    <th scope="col" class="text-center">{{__("Update date")}}</th>
                    @if (levelcheck('Super'))
                    <th scope="col" class="text-right">{{__("Actions")}}</th>
                    @endif
                </tr>
            </thead>
            <tbody>
                @foreach($users as $user)  
                <tr>
                    <td>{{ $user->id }}</td>
                    <td>{{ $user->name }}</td>
                    <td>{{ $user->email }}</td>
                    <td>
                        @foreach ($user->roles->sortByDesc('name') as $rol)
                        @switch($rol->id)
                        @case(2)
                        {{ __("Administrator") }},
                        @break
                        @case(3)
                        {{ __("Storer") }},
                        @break
                        @case(4)
                        {{ __("Buyer") }},
                        @break
                        @default
                        
                        @endswitch
                        @endforeach
                    </td>
                    <td class="text-center">{{ $user->created_at }}</td>
                    <td class="text-center">{{ $user->updated_at }}</td>
                    @if (levelcheck('Super'))
                    <td class="text-right">
                        <a class="btn-sm btn btn-dark" data-placement="left" data-tt="tooltip" title="{{__('Edit user')}}" href="{{ route('users.edit',$user->id) }}">
                            <i class="fa fa-pen"></i>
                        </a>
                        <form method="POST" class="d-inline-block">
                            @method('DELETE')
                            <button class="btn-sm btn btn-danger delete" data-placement="left" data-tt="tooltip" title="{{__('Delete user')}}" data-id="{{ $user->id }}" data-ts="{{__('Are you sure?')}}"  data-tx='{{__("You won't be able to revert this!")}}' data-ty="{{__('Yes')}}">
                                <i class="fa fa-trash"></i>
                            </button>
                            @csrf
                        </form>
                    </td>
                    @endif
                </tr>
                @endforeach
            </tbody>
        </table>

    </div>
</div>

<div class="table-responsive">
    {{ $users->onEachSide(2)->links() }}
</div>
@else
<div id="load" class="position-relative">
    <div class="text-center mt-4">
        <p>
            {{__("No record found")}}
        </p>
        @if (levelcheck('Super'))
        <a class="btn  btn-sm btn-primary mt-1" href="{{ route('users.create') }}">
            <i class="fa fa-plus"></i> {{__("Add user")}}
        </a>
        @endif
    </div>
</div>
@endif